// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using berozkala_backend.DbContextes;

#nullable disable

namespace berozkala_backend.Migrations
{
    [DbContext(typeof(BerozkalaDb))]
    [Migration("20250715223203_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("berozkala_backend.Entities.Product.AttributeSubset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductAttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.ToTable("AttributeSubsets");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateToAdd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("GuId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ImagesUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInvisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.ProductGarranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GarrantyCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductGarrantys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.AttributeSubset", b =>
                {
                    b.HasOne("berozkala_backend.Entities.Product.ProductAttribute", null)
                        .WithMany("Subsets")
                        .HasForeignKey("ProductAttributeId");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.ProductAttribute", b =>
                {
                    b.HasOne("berozkala_backend.Entities.Product.Product", null)
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.ProductGarranty", b =>
                {
                    b.HasOne("berozkala_backend.Entities.Product.Product", null)
                        .WithMany("ProductGarrantys")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.Product", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductGarrantys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.Product.ProductAttribute", b =>
                {
                    b.Navigation("Subsets");
                });
#pragma warning restore 612, 618
        }
    }
}
