// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using berozkala_backend.DbContextes;

#nullable disable

namespace berozkala_backend.Migrations
{
    [DbContext(typeof(BerozkalaDb))]
    [Migration("20251014234226_UpdateFluentApli12")]
    partial class UpdateFluentApli12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("berozkala_backend.Entities.AccountsEntities.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminRole")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfSingup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OptLifeTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("berozkala_backend.Entities.AccountsEntities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountRole")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfSingup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OptLifeTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OrderEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasketTotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateToAdd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentInformaationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipmentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DiscountCodeId");

                    b.HasIndex("PaymentInformaationId");

                    b.HasIndex("ReceiverAddressId");

                    b.HasIndex("ShipmentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OrderEntities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductGarrantyId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductGarrantyId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdminAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.DiscountCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndOfCredit")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.FavoriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("FavoriteProduct");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.PaymentInformaation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTrackingCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeymentStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("PaymentInformaation");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.PeymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PeymentMethods");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.ShippingMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShipmentCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShippingMethods");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.SubmitedDiscountCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscountCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("SubmitedDiscountCode");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.AttributeSubset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("ProductSubsetAttributes");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.BasketProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedGarrantyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SelectedGarrantyId");

                    b.HasIndex("UserId");

                    b.ToTable("BasketsProducts");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateToAdd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductGarranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GarrantyCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductGarrantys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ProductsSubCategorys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("SubCategorys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OrderEntities.Order", b =>
                {
                    b.HasOne("berozkala_backend.Entities.AccountsEntities.UserAccount", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.OtherEntities.DiscountCode", "DiscountCode")
                        .WithMany()
                        .HasForeignKey("DiscountCodeId");

                    b.HasOne("berozkala_backend.Entities.OtherEntities.PaymentInformaation", "PaymentInformaation")
                        .WithMany()
                        .HasForeignKey("PaymentInformaationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.OtherEntities.Address", "ReceiverAddress")
                        .WithMany()
                        .HasForeignKey("ReceiverAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.OtherEntities.ShippingMethod", "ShipmentMethod")
                        .WithMany()
                        .HasForeignKey("ShipmentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DiscountCode");

                    b.Navigation("PaymentInformaation");

                    b.Navigation("ReceiverAddress");

                    b.Navigation("ShipmentMethod");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OrderEntities.OrderItem", b =>
                {
                    b.HasOne("berozkala_backend.Entities.OrderEntities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("berozkala_backend.Entities.ProductEntities.ProductGarranty", "ProductGarranty")
                        .WithMany()
                        .HasForeignKey("ProductGarrantyId");

                    b.Navigation("ProductGarranty");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.Address", b =>
                {
                    b.HasOne("berozkala_backend.Entities.AccountsEntities.AdminAccount", null)
                        .WithMany("Addresses")
                        .HasForeignKey("AdminAccountId");

                    b.HasOne("berozkala_backend.Entities.AccountsEntities.UserAccount", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.FavoriteProduct", b =>
                {
                    b.HasOne("berozkala_backend.Entities.AccountsEntities.UserAccount", "UserAccount")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.PaymentInformaation", b =>
                {
                    b.HasOne("berozkala_backend.Entities.OtherEntities.PeymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OtherEntities.SubmitedDiscountCode", b =>
                {
                    b.HasOne("berozkala_backend.Entities.OtherEntities.DiscountCode", "DiscountCode")
                        .WithMany()
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.AccountsEntities.UserAccount", "User")
                        .WithMany("SubmitedDiscountCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.AttributeSubset", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.ProductAttribute", "Attribute")
                        .WithMany("Subsets")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.BasketProduct", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Product", "Product")
                        .WithMany("BasketsProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.ProductEntities.ProductGarranty", "SelectedGarranty")
                        .WithMany()
                        .HasForeignKey("SelectedGarrantyId");

                    b.HasOne("berozkala_backend.Entities.AccountsEntities.UserAccount", "User")
                        .WithMany("BasketsProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SelectedGarranty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductAttribute", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductGarranty", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Product", "Product")
                        .WithMany("Garrantys")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductImage", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Product", "Product")
                        .WithMany("ImagesUrls")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductSubCategory", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Product", "Product")
                        .WithMany("ProductsSubCategorys")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("berozkala_backend.Entities.ProductEntities.SubCategory", "SubCategory")
                        .WithMany("ProductsSubCategorys")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.SubCategory", b =>
                {
                    b.HasOne("berozkala_backend.Entities.ProductEntities.Category", "ProductCategory")
                        .WithMany("SubCategorys")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("berozkala_backend.Entities.AccountsEntities.AdminAccount", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("berozkala_backend.Entities.AccountsEntities.UserAccount", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BasketsProducts");

                    b.Navigation("FavoriteProducts");

                    b.Navigation("Orders");

                    b.Navigation("SubmitedDiscountCodes");
                });

            modelBuilder.Entity("berozkala_backend.Entities.OrderEntities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.Category", b =>
                {
                    b.Navigation("SubCategorys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("BasketsProducts");

                    b.Navigation("Garrantys");

                    b.Navigation("ImagesUrls");

                    b.Navigation("ProductsSubCategorys");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.ProductAttribute", b =>
                {
                    b.Navigation("Subsets");
                });

            modelBuilder.Entity("berozkala_backend.Entities.ProductEntities.SubCategory", b =>
                {
                    b.Navigation("ProductsSubCategorys");
                });
#pragma warning restore 612, 618
        }
    }
}
